services:
  db:
    image: postgres:15
    container_name: medkids_db
    environment:
      POSTGRES_USER: medkids
      POSTGRES_PASSWORD: medkids
      POSTGRES_DB: medkids
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: medkids_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
